### ISSUE TITLE
NullPointerException on  Capability<IMana> MANA_CAP = null

### ISSUE THREAD

**Issue by CasparChou** [mchorse/capabilities#1]
when player login, it will occur an NullPointerException on
```java
public static final Capability<ISidedInventory> INVENTORY_CAP = null;
```
Is that something I missing ?
Seems that assign a `null` when declaring  `INVENTORY_CAP` is got some error

referencing to your tutorial:
https://github.com/mchorse/capabilities/blob/88ca9a7eb7279a56d2e6dfe8b99d1dae33fab821/src/main/java/mchorse/capabilities/capabilities/ManaProvider.java

here is my code
```java
public class InventoryProvider  implements ICapabilitySerializable<NBTTagList>{

    @CapabilityInject(ISidedInventory.class)
    public static final Capability<ISidedInventory> INVENTORY_CAP = null;
    private ISidedInventory instance = INVENTORY_CAP.getDefaultInstance();

    @Override
    public boolean hasCapability(Capability<?> capability, @Nullable EnumFacing facing) {
        return capability == INVENTORY_CAP;
    }

    @Override
    public <T> T getCapability(Capability<T> capability, @Nullable EnumFacing facing) {
        return capability == INVENTORY_CAP ? INVENTORY_CAP.<T> cast(this.instance) : null;
    }

    @Override
    public NBTTagList serializeNBT() {
        return (NBTTagList) INVENTORY_CAP.getStorage().writeNBT(INVENTORY_CAP, this.instance, null);
    }

    @Override
    public void deserializeNBT(NBTTagList nbt) {
        INVENTORY_CAP.getStorage().readNBT(INVENTORY_CAP, this.instance, null, (NBTTagList)nbt);
    }
}
```

also, the error log

```
[14:49:59] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.AttachCapabilitiesEvent$Entity@2407c431:
java.lang.NullPointerException
	at lab.tenoz.rainsia.entity.player.InventoryProvider.<init>(InventoryProvider.java:19) ~[InventoryProvider.class:?]
	at lab.tenoz.rainsia.events.handler.CapabilityHandler.attachCapability(CapabilityHandler.java:21) ~[CapabilityHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_10_CapabilityHandler_attachCapability_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:565) [ForgeEventFactory.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:550) [ForgeEventFactory.class:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:252) [Entity.class:?]
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:192) [EntityLivingBase.class:?]
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:181) [EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:162) [EntityPlayerMP.class:?]
	at net.minecraft.server.management.PlayerList.createPlayerForUser(PlayerList.java:525) [PlayerList.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:137) [NetHandlerLoginServer.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:64) [NetHandlerLoginServer.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:308) [NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:195) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:806) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:408) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
```

**Comment by mchorse** [comment]
@CasparChou have you registered your capability via CapabilityManager? Just like [here](https://github.com/mchorse/capabilities/blob/master/src/main/java/mchorse/capabilities/CommonProxy.java#L17):


```java
public void init()
{
    CapabilityManager.INSTANCE.register(IMana.class, new ManaStorage(), Mana.class);

    MinecraftForge.EVENT_BUS.register(new CapabilityHandler());
    MinecraftForge.EVENT_BUS.register(new EventHandler());
}
```

I think this is your problem. You added the annotation, but forgot to register the capability itself. 😃

**Comment by CasparChou** [comment]
Yes, I already registered that 
I think the problem is ISidedInventory could not use directly
I replaced ISidedInventory from a new interface which implement ISidedInventory  then it work
